import { useState, useEffect } from "react";
import { Card, Loader, FormField } from "../components";

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />);
  }

  return (
    <h2 className="mt-5 font-bold text-[#6449ff] text-xl uppercase:">
      {title}
    </h2>
  );
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);

  const [searchText, setsearchText] = useState("abcd");

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className=" font-extrabold mt-[-10px] text-[32px] text-[#222328] ">
          The Community Showcase
        </h1>
        <p className=" mt-2 text-[#666e75] text-[16px] max-w-[500px]">
          Browse through a collection of imaginative and visually stunning
          images generated by DALL-E AI
        </p>
      </div>

      <div className=" mt-16 ">
        <FormField />
      </div>

      <div className=" mt-10 ">
        {loading ? (
          <div className=" flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className=" font-medium text-xl text-[#666e75] mb-3">
                Showing results for{" "}
                <span className=" text-[#222328]">{searchText}</span>
              </h2>
            )}
            <div className=" grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? (
                <RenderCards data={[1,2,3,4,5]} title="no search results found" />
              ) : (
                <RenderCards data={[1,2,3,4,5]} title="No Posts Found" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
